[package]
name = "agent_directory_integrity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[lints]
workspace = true

[dependencies]
serde.workspace = true
hdi.workspace = true
holochain_serialized_bytes.workspace = true
